// Generated by luminjs
import { h, hydrate as __hydrate } from '@luminjs/runtime';
import { StyledCounter } from './StyledCounter.lumin';
import { FormDemo } from './FormDemo.lumin';

function App(props = {}) {
  return h('div', null, [
    `
  `,
    h(StyledCounter, null),
    `
  `,
    h(FormDemo, null),
    `
`
  ]);
}
export default App;
export { App };

export function hydrate(root, props) {
  __hydrate(root, App, props);
}
