// Generated by luminjs
import { h, hydrate as __hydrate } from '@luminjs/runtime';

function Counter(props = {}) {
  // --- User Script ---
  
  const count = signal(0)
  
  function inc() {
    count(count() + 1)
  }
  function dec() {
    count(count() - 1)
  }

  return h('div', null, [
    `
  `,
    h('h1', null, [
      `Count: `,
      () => (count())
    ]),
    `
  `,
    h('button', {
      'onClick': inc
    }, [
      `Increment`
    ]),
    `
  `,
    h('button', {
      'onClick': () => { count(count() - 1) }
    }, [
      `Decrement`
    ]),
    `
  `,
    h('button', {
      'onClick': () => { console.log("Logging to console") }
    }, [
      `Log`
    ]),
    `
`
  ]);
}
export default Counter;
export { Counter };

export function hydrate(root, props) {
  __hydrate(root, Counter, props);
}
