// Generated by luminjs
import { h, hydrate as __hydrate } from '@luminjs/runtime';

  import { signal, computed, batch, effect, store, persist } from "@luminjs/runtime";
function FormDemo(props = {}) {
  // --- User Script ---
  
  
    // Signals
    const name = signal("");
    const age = signal(25);
    const accepted = signal(false);
  
    // Computed
    const greeting = computed(() => {
      const n = name();
      return n ? `Hello, ${n}!` : "Enter your name...";
    });
  
    // Store with persistence
    const formStore = store({
      email: "",
      theme: "light",
      submissions: 0,
    });
  
    persist(formStore, { key: "lumin-form-demo" });
  
    // Batch example
    function resetAll() {
      batch(() => {
        name("");
        age(25);
        accepted(false);
        formStore.reset();
      });
    }
  
    function handleSubmit() {
      formStore.set("submissions", formStore.get("submissions") + 1);
      console.log("Submitted!", {
        name: name(),
        age: age(),
        accepted: accepted(),
        email: formStore.get("email"),
      });
    }

  // Styles
  if (typeof document !== 'undefined') {
    const styleId = 'lumin-style-formdemo';
    if (!document.getElementById(styleId)) {
      const s = document.createElement('style');
      s.id = styleId;
      s.textContent = `
  .form-demo {
    max-width: 480px;
    margin: 2rem auto;
    padding: 2rem;
    border-radius: 12px;
    background: #1a1a2e;
    color: #eee;
    font-family: 'Segoe UI', sans-serif;
    box-shadow: 0 8px 32px rgba(0,0,0,0.3);
  }
  h2 { margin: 0 0 1.5rem; color: #e94560; }
  .field { margin-bottom: 1rem; }
  .field label {
    display: block;
    font-size: 0.85rem;
    color: #aaa;
    margin-bottom: 4px;
  }
  .field input, .field select {
    width: 100%;
    padding: 10px 12px;
    border: 1px solid #333;
    border-radius: 6px;
    background: #16213e;
    color: #eee;
    font-size: 1rem;
    box-sizing: border-box;
  }
  .field input:focus {
    outline: none;
    border-color: #e94560;
  }
  .checkbox-field {
    display: flex;
    align-items: center;
    gap: 8px;
    margin-bottom: 1rem;
  }
  .checkbox-field input[type="checkbox"] {
    width: 18px;
    height: 18px;
    accent-color: #e94560;
  }
  .greeting {
    padding: 12px;
    border-radius: 6px;
    background: #0f3460;
    margin-bottom: 1rem;
    font-size: 1.1rem;
  }
  .actions {
    display: flex;
    gap: 8px;
    margin-top: 1rem;
  }
  button {
    padding: 10px 20px;
    border: none;
    border-radius: 6px;
    cursor: pointer;
    font-size: 0.95rem;
    transition: transform 0.1s;
  }
  button:active { transform: scale(0.97); }
  .btn-primary { background: #e94560; color: white; }
  .btn-secondary { background: #333; color: #ccc; }
  .stats {
    margin-top: 1.5rem;
    padding-top: 1rem;
    border-top: 1px solid #333;
    font-size: 0.85rem;
    color: #888;
  }
`;
      document.head.appendChild(s);
    }
  }

  return h('div', {
    'class': 'form-demo'
  }, [
    `
  `,
    h('h2', null, [
      `LuminJS Form Demo`
    ]),
    `

  `,
    h('div', {
      'class': 'greeting'
    }, [
      () => (greeting())
    ]),
    `

  `,
    h('div', {
      'class': 'field'
    }, [
      `
    `,
      h('label', null, [
        `Name`
      ]),
      `
    `,
      h('input', {
        'type': 'text',
        'bind:value': name
      }),
      `
  `
    ]),
    `

  `,
    h('div', {
      'class': 'field'
    }, [
      `
    `,
      h('label', null, [
        `Age`
      ]),
      `
    `,
      h('input', {
        'type': 'number',
        'bind:value': age
      }),
      `
  `
    ]),
    `

  `,
    h('div', {
      'class': 'field'
    }, [
      `
    `,
      h('label', null, [
        `Email (stored)`
      ]),
      `
    `,
      h('input', {
        'type': 'email',
        'bind:value': formStore.signal("email")
      }),
      `
  `
    ]),
    `

  `,
    h('div', {
      'class': 'checkbox-field'
    }, [
      `
    `,
      h('input', {
        'type': 'checkbox',
        'bind:checked': accepted
      }),
      `
    `,
      h('label', null, [
        `I accept the terms`
      ]),
      `
  `
    ]),
    `

  `,
    h('div', {
      'class': 'actions'
    }, [
      `
    `,
      h('button', {
        'class': 'btn-primary',
        'onClick': handleSubmit
      }, [
        `Submit`
      ]),
      `
    `,
      h('button', {
        'class': 'btn-secondary',
        'onClick': resetAll
      }, [
        `Reset All`
      ]),
      `
  `
    ]),
    `

  `,
    h('div', {
      'class': 'stats'
    }, [
      `
    Submissions: `,
      () => (formStore.get("submissions")),
      `
  `
    ]),
    `
`
  ]);
}
export default FormDemo;
export { FormDemo };

export function hydrate(root, props) {
  __hydrate(root, FormDemo, props);
}
