// Generated by luminjs
import * as __LUMIN__ from '@luminjs/runtime';

function MyCard(props = {}) {
  let { title, count, active = false } = props;
  if (title === undefined) throw new Error("LuminJS: Component 'MyCard' missing required prop 'title'");
  if (count === undefined) throw new Error("LuminJS: Component 'MyCard' missing required prop 'count'");


  // Styles
  if (typeof document !== 'undefined') {
    const styleId = 'lumin-style-mycard';
    if (!document.getElementById(styleId)) {
      const s = document.createElement('style');
      s.id = styleId;
      s.textContent = `
  .card {
    padding: 15px;
    margin: 15px 0;
    border-radius: 8px;
    font-family: sans-serif;
  }
  h2 {
    margin-top: 0;
    color: #333;
  }
`;
      document.head.appendChild(s);
    }
  }

  return __LUMIN__.h('div', null, [
    __LUMIN__.h('div', {
      'class': 'card',
      'style': () => (active ? "border: 2px solid blue; background: #f0f8ff;" : "border: 1px solid #ccc;")
    }, [
      `
  `,
      __LUMIN__.h('h2', null, [
        () => (title)
      ]),
      `
  `,
      __LUMIN__.h('p', null, [
        `Count Value: `,
        () => (count)
      ]),
      `
  `,
      __LUMIN__.h('p', null, [
        `Status: `,
        () => (active ? "Active" : "Inactive")
      ]),
      `
`
    ]),
    `

`
  ]);
}
export default MyCard;
export { MyCard };

export function hydrate(root, props) {
  __LUMIN__.hydrate(root, MyCard, props);
}
