// Generated by luminjs
import * as __LUMIN__ from '@luminjs/runtime';
import MyCard from './MyCard.lumin';
import { signal } from "@luminjs/runtime";

function PropsDemo(props = {}) {
    const count = signal(0);
    const inc = () => count(count() + 1);
    const dec = () => count(count() - 1);

  // Styles
  if (typeof document !== 'undefined') {
    const styleId = 'lumin-style-propsdemo';
    if (!document.getElementById(styleId)) {
      const s = document.createElement('style');
      s.id = styleId;
      s.textContent = `
  .container {
    max-width: 600px;
    margin: 0 auto;
    padding: 20px;
  }
  .controls {
    margin: 10px 0;
  }
  button {
    padding: 8px 16px;
    margin-right: 10px;
    cursor: pointer;
  }
  .note {
    font-size: 0.9em;
    color: #666;
    font-style: italic;
    margin-top: 20px;
  }
`;
      document.head.appendChild(s);
    }
  }

  return __LUMIN__.h('div', null, [
    __LUMIN__.h('div', {
      'class': 'container'
    }, [
      `
  `,
      __LUMIN__.h('h1', null, [
        `Component Props Demo`
      ]),
      `
  `,
      __LUMIN__.h('p', null, [
        `Parent Counter: `,
        __LUMIN__.h('strong', null, [
          () => (count())
        ])
      ]),
      `
  
  `,
      __LUMIN__.h('div', {
        'class': 'controls'
      }, [
        `
    `,
        __LUMIN__.h('button', {
          'onClick': inc
        }, [
          `Parent +`
        ]),
        `
    `,
        __LUMIN__.h('button', {
          'onClick': dec
        }, [
          `Parent -`
        ]),
        `
  `
      ]),
      `

  `,
      __LUMIN__.h('hr', null),
      `

  `,
      __LUMIN__.h(MyCard, {
        'title': 'Reactive Card (Props)',
        'count': () => (count()),
        'active': () => (true)
      }),
      `
  
  `,
      __LUMIN__.h(MyCard, {
        'title': 'Static Card (Default Actives value)',
        'count': () => (100)
      }),
      `

  `,
      __LUMIN__.h('p', {
        'class': 'note'
      }, [
        `Note: If you omit 'title' or 'count', an error will be thrown (see console).`
      ]),
      `
`
    ]),
    `

`
  ]);
}
export default PropsDemo;
export { PropsDemo };

export function hydrate(root, props) {
  __LUMIN__.hydrate(root, PropsDemo, props);
}
