// Generated by luminjs
import { h, hydrate as __hydrate } from '@luminjs/runtime';
import { Counter } from './Counter.lumin';

  import { signal } from "@luminjs/runtime";
function StyledCounter(props = {}) {
  // --- User Script ---
  
    const count = signal(0);
    const inc = () => count(count() + 1);
    const dec = () => count(count() - 1);
    
    const title = "Styled Counter";
    const color = signal("blue");

  // Styles
  if (typeof document !== 'undefined') {
    const styleId = 'lumin-style-styledcounter';
    if (!document.getElementById(styleId)) {
      const s = document.createElement('style');
      s.id = styleId;
      s.textContent = `
  .counter {
    border: 2px solid #ccc;
    padding: 20px;
    border-radius: 8px;
    text-align: center;
    font-family: sans-serif;
  }
  .display {
    font-size: 2rem;
    margin: 10px 0;
  }
  button {
    padding: 10px 20px;
    font-size: 1rem;
    cursor: pointer;
    margin: 0 5px;
  }
`;
      document.head.appendChild(s);
    }
  }

  return h('div', {
    'class': 'counter'
  }, [
    `
  `,
    h('h1', null, [
      () => (title)
    ]),
    `
  `,
    h('div', {
      'class': 'display',
      'style': () => ('color: ' + color())
    }, [
      `
    Count: `,
      () => (count()),
      `
  `
    ]),
    `
  `,
    h('button', {
      'onClick': inc
    }, [
      `Increment`
    ]),
    `
  `,
    h('button', {
      'onClick': dec
    }, [
      `Decrement`
    ]),
    `
  `,
    h('button', {
      'onClick': () => color(color() === 'blue' ? 'red' : 'blue')
    }, [
      `
    Toggle Color
  `
    ]),
    `
`
  ]);
}
export default StyledCounter;
export { StyledCounter };

export function hydrate(root, props) {
  __hydrate(root, StyledCounter, props);
}
