// Generated by LumixJS
import * as __LUMIX__ from 'lumix-js';

function about(props = {}) {
  // Styles
  if (typeof document !== 'undefined') {
    const styleId = 'lumix-style-about';
    if (!document.getElementById(styleId)) {
      const s = document.createElement('style');
      s.id = styleId;
      s.textContent = `
  .page { padding: 2rem; font-family: system-ui, sans-serif; }
`;
      document.head.appendChild(s);
    }
  }

  return __LUMIX__.h(__LUMIX__.Fragment, null, __LUMIX__.h('div', {
    'class': 'page'
  }, [
    `
  `,
    __LUMIX__.h('h1', null, [
      `About`
    ]),
    `
  `,
    __LUMIX__.h('p', null, [
      `This is the about page.`
    ]),
    `
`
  ]), `

`);
}
export default about;
export { about };
const __LUMIX_ROOT__ = about;

export function hydrate(root, props) {
  __LUMIX__.hydrate(root, about, props);
}
