// Generated by LumixJS
import * as __LUMIX__ from 'lumix-js';
import { signal } from "lumix-js";

function index(props = {}) {
  const count = signal(0);

  // Styles
  if (typeof document !== 'undefined') {
    const styleId = 'lumix-style-index';
    if (!document.getElementById(styleId)) {
      const s = document.createElement('style');
      s.id = styleId;
      s.textContent = `
  .page {
    max-width: 640px;
    margin: 0 auto;
    padding: 2rem;
    font-family: system-ui, sans-serif;
  }
  h1 { color: #4f46e5; }
  code { background: #f3f4f6; padding: 0.2rem 0.4rem; border-radius: 4px; }
  button {
    margin-top: 1rem;
    padding: 0.5rem 1rem;
    background: #4f46e5;
    color: white;
    border: none;
    border-radius: 6px;
    cursor: pointer;
  }
`;
      document.head.appendChild(s);
    }
  }

  return __LUMIX__.h(__LUMIX__.Fragment, null, __LUMIX__.h('div', {
    'class': 'page'
  }, [
    `
  `,
    __LUMIX__.h('h1', null, [
      `Lumix`
    ]),
    `
  `,
    __LUMIX__.h('p', null, [
      `Meta-framework template. Edit `,
      __LUMIX__.h('code', null, [
        `src/routes/index.lumix`
      ]),
      `.`
    ]),
    `
  `,
    __LUMIX__.h('button', {
      'onclick': ()=>count(count() + 1)
    }, [
      `Count: `,
      () => (count())
    ]),
    `
`
  ]), `

`);
}
export default index;
export { index };
const __LUMIX_ROOT__ = index;

export function hydrate(root, props) {
  __LUMIX__.hydrate(root, index, props);
}
