// Generated by LumixJS
import * as __LUMIX__ from 'lumix-js';
import MainLayout from '/src/layouts/MainLayout.lumix';
import Counter from '/src/components/Counter.lumix';
import { signal } from "lumix-js";

function about(props = {}) {
  "use server";
  const serverTime = new Date().toISOString();
  const requestCount = signal(0);

  // Styles
  if (typeof document !== 'undefined') {
    const styleId = 'lumix-style-about';
    if (!document.getElementById(styleId)) {
      const s = document.createElement('style');
      s.id = styleId;
      s.textContent = `
  .page {
    font-family: system-ui, -apple-system, sans-serif;
  }
  
  .hero {
    text-align: center;
    margin-bottom: 4rem;
  }
  
  .hero-logo {
    display: block;
    margin: 0 auto 2rem;
    opacity: 0.9;
  }
  
  h1 {
    font-size: 3.5rem;
    margin: 0 0 1rem 0;
    background: linear-gradient(135deg, #10b981 0%, #059669 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
    font-weight: 800;
    letter-spacing: -0.02em;
  }
  
  .subtitle {
    font-size: 1.25rem;
    color: #a1a1aa;
    margin: 0;
    font-weight: 400;
  }
  
  .info-card {
    background: rgba(24, 24, 27, 0.6);
    border: 1px solid rgba(16, 185, 129, 0.2);
    border-radius: 16px;
    padding: 2rem;
    margin: 3rem 0;
    backdrop-filter: blur(12px);
  }
  
  .card-icon {
    width: 48px;
    height: 48px;
    background: linear-gradient(135deg, #10b981 0%, #059669 100%);
    border-radius: 12px;
    display: flex;
    align-items: center;
    justify-content: center;
    margin-bottom: 1.5rem;
  }
  
  .card-icon svg {
    color: white;
  }
  
  .card-icon img {
    display: block;
    filter: brightness(0) saturate(100%) invert(100%);
  }
  
  .info-card h2 {
    margin: 0 0 1rem 0;
    color: #e4e4e7;
    font-size: 1.5rem;
    font-weight: 700;
  }
  
  .info-card p {
    color: #a1a1aa;
    line-height: 1.6;
    margin: 0 0 1.5rem 0;
  }
  
  .info-card ul {
    list-style: none;
    margin: 0;
    padding: 0;
    display: flex;
    flex-direction: column;
    gap: 0.75rem;
  }
  
  .info-card li {
    display: flex;
    align-items: center;
    gap: 0.75rem;
    color: #d4d4d8;
  }
  
  .info-card li svg {
    color: #10b981;
    flex-shrink: 0;
  }
  
  .info-card li img {
    flex-shrink: 0;
    filter: brightness(0) saturate(100%) invert(64%) sepia(98%) saturate(1000%) hue-rotate(115deg) brightness(96%) contrast(89%);
  }
  
  .server-info {
    background: rgba(24, 24, 27, 0.4);
    border: 1px solid rgba(255, 255, 255, 0.1);
    border-radius: 16px;
    padding: 2rem;
    margin: 3rem 0;
  }
  
  .server-info h3 {
    margin: 0 0 1.5rem 0;
    color: #e4e4e7;
    font-size: 1.25rem;
    font-weight: 600;
  }
  
  .info-grid {
    display: grid;
    gap: 1rem;
  }
  
  .info-item {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 1rem;
    background: rgba(39, 39, 42, 0.6);
    border-radius: 12px;
    border: 1px solid rgba(255, 255, 255, 0.05);
  }
  
  .info-label {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    font-weight: 600;
    color: #a1a1aa;
  }
  
  .info-label svg {
    color: #10b981;
  }
  
  .info-label img {
    filter: brightness(0) saturate(100%) invert(64%) sepia(98%) saturate(1000%) hue-rotate(115deg) brightness(96%) contrast(89%);
  }
  
  .info-value {
    font-family: 'Courier New', monospace;
    color: #10b981;
    font-weight: 500;
    font-size: 0.875rem;
  }
  
  .hint {
    margin: 1.5rem 0 0 0;
    padding: 1rem;
    background: rgba(234, 179, 8, 0.1);
    border-radius: 12px;
    border: 1px solid rgba(234, 179, 8, 0.2);
    color: #fbbf24;
    font-size: 0.875rem;
    display: flex;
    align-items: center;
    gap: 0.75rem;
  }
  
  .hint svg {
    flex-shrink: 0;
  }
  
  .hint img {
    flex-shrink: 0;
    filter: brightness(0) saturate(100%) invert(79%) sepia(61%) saturate(1000%) hue-rotate(359deg) brightness(102%) contrast(97%);
  }
  
  .demo-section {
    margin: 4rem 0;
  }
  
  .demo-section h2 {
    text-align: center;
    margin-bottom: 1rem;
    color: #e4e4e7;
    font-size: 2rem;
    font-weight: 700;
  }
  
  .demo-description {
    text-align: center;
    margin-bottom: 2rem;
    color: #a1a1aa;
  }
`;
      document.head.appendChild(s);
    }
  }

  return __LUMIX__.h(__LUMIX__.Fragment, null, __LUMIX__.h(MainLayout, {
    'children': () => [
      `
  `,
      __LUMIX__.h('div', {
        'class': 'page'
      }, [
        `
    `,
        __LUMIX__.h('div', {
          'class': 'hero'
        }, [
          `
      `,
          __LUMIX__.h('img', {
            'src': '/icons/logo.svg',
            'alt': 'Lumix',
            'class': 'hero-logo',
            'width': '80',
            'height': '80'
          }),
          `
      `,
          __LUMIX__.h('h1', null, [
            `About`
          ]),
          `
      `,
          __LUMIX__.h('p', {
            'class': 'subtitle'
          }, [
            `Server-Side Rendering in action`
          ]),
          `
    `
        ]),
        `
    
    `,
        __LUMIX__.h('div', {
          'class': 'info-card ssr'
        }, [
          `
      `,
          __LUMIX__.h('div', {
            'class': 'card-icon'
          }, [
            `
        `,
            __LUMIX__.h('img', {
              'src': '/icons/monitor.svg',
              'alt': '',
              'width': '24',
              'height': '24'
            }),
            `
      `
          ]),
          `
      `,
          __LUMIX__.h('h2', null, [
            `Server-Side Rendering (SSR)`
          ]),
          `
      `,
          __LUMIX__.h('p', null, [
            `This page is rendered on the server for every request, then hydrated on the client for interactivity.`
          ]),
          `
      `,
          __LUMIX__.h('ul', null, [
            `
        `,
            __LUMIX__.h('li', null, [
              `
          `,
              __LUMIX__.h('img', {
                'src': '/icons/check.svg',
                'alt': '',
                'width': '16',
                'height': '16'
              }),
              `
          Dynamic server-side data
        `
            ]),
            `
        `,
            __LUMIX__.h('li', null, [
              `
          `,
              __LUMIX__.h('img', {
                'src': '/icons/check.svg',
                'alt': '',
                'width': '16',
                'height': '16'
              }),
              `
          Fresh content on every request
        `
            ]),
            `
        `,
            __LUMIX__.h('li', null, [
              `
          `,
              __LUMIX__.h('img', {
                'src': '/icons/check.svg',
                'alt': '',
                'width': '16',
                'height': '16'
              }),
              `
          Client-side hydration
        `
            ]),
            `
      `
          ]),
          `
    `
        ]),
        `
    
    `,
        __LUMIX__.h('div', {
          'class': 'server-info'
        }, [
          `
      `,
          __LUMIX__.h('h3', null, [
            `Server Information`
          ]),
          `
      `,
          __LUMIX__.h('div', {
            'class': 'info-grid'
          }, [
            `
        `,
            __LUMIX__.h('div', {
              'class': 'info-item'
            }, [
              `
          `,
              __LUMIX__.h('div', {
                'class': 'info-label'
              }, [
                `
            `,
                __LUMIX__.h('img', {
                  'src': '/icons/clock.svg',
                  'alt': '',
                  'width': '16',
                  'height': '16'
                }),
                `
            `,
                __LUMIX__.h('span', null, [
                  `Server Time`
                ]),
                `
          `
              ]),
              `
          `,
              __LUMIX__.h('span', {
                'class': 'info-value'
              }, [
                () => (serverTime)
              ]),
              `
        `
            ]),
            `
        `,
            __LUMIX__.h('div', {
              'class': 'info-item'
            }, [
              `
          `,
              __LUMIX__.h('div', {
                'class': 'info-label'
              }, [
                `
            `,
                __LUMIX__.h('img', {
                  'src': '/icons/box.svg',
                  'alt': '',
                  'width': '16',
                  'height': '16'
                }),
                `
            `,
                __LUMIX__.h('span', null, [
                  `Rendering Mode`
                ]),
                `
          `
              ]),
              `
          `,
              __LUMIX__.h('span', {
                'class': 'info-value'
              }, [
                `SSR (Dynamic)`
              ]),
              `
        `
            ]),
            `
      `
          ]),
          `
      `,
          __LUMIX__.h('div', {
            'class': 'hint'
          }, [
            `
        `,
            __LUMIX__.h('img', {
              'src': '/icons/help-circle.svg',
              'alt': '',
              'width': '16',
              'height': '16'
            }),
            `
        `,
            __LUMIX__.h('span', null, [
              `Reload this page to see the timestamp update`
            ]),
            `
      `
          ]),
          `
    `
        ]),
        `
    
    `,
        __LUMIX__.h('div', {
          'class': 'demo-section'
        }, [
          `
      `,
          __LUMIX__.h('h2', null, [
            `Client-Side Interactivity`
          ]),
          `
      `,
          __LUMIX__.h('p', {
            'class': 'demo-description'
          }, [
            `Even though this page is server-rendered, it's fully interactive on the client:`
          ]),
          `
      `,
          __LUMIX__.h(Counter, {
            'initialCount': 10,
            'label': 'SSR Counter'
          }),
          `
    `
        ]),
        `
  `
      ]),
      `
`
    ]
  }), `

`);
}
export default about;
export { about };
const __LUMIX_ROOT__ = about;

// Head metadata
export const head = {title: "About - Lumix Framework", meta: [{"content":"Learn about Lumix SSR capabilities and server-side rendering","name":"description"},{"property":"og:title","content":"About Lumix"},{"content":"Server-side rendering with Lumix","property":"og:description"}]};

export function hydrate(root, props) {
  __LUMIX__.hydrate(root, about, props);
}
