// Generated by LumixJS
import * as __LUMIX__ from 'lumix-js';
import { signal } from "lumix-js";

function about(props = {}) {
  "use static";
  const serverTime = new Date().toISOString();
  const userAgent = typeof navigator !== 'undefined' ? navigator.userAgent : 'Server-Side';
  const count = signal(0);

  // Styles
  if (typeof document !== 'undefined') {
    const styleId = 'lumix-style-about';
    if (!document.getElementById(styleId)) {
      const s = document.createElement('style');
      s.id = styleId;
      s.textContent = `
  .page { 
    padding: 2rem; 
    font-family: system-ui, sans-serif; 
    max-width: 640px;
    margin: 0 auto;
  }
  
  h1 { 
    color: #059669; 
  }
  
  .nav {
    margin-top: 2rem;
    padding: 1rem;
    background: #f0fdf4;
    border-radius: 8px;
  }
  
  .nav a {
    color: #059669;
    text-decoration: none;
    font-weight: 500;
  }
  
  .nav a:hover {
    text-decoration: underline;
  }
  
  button {
    margin-top: 1rem;
    padding: 0.5rem 1rem;
    background: #059669;
    color: white;
    border: none;
    border-radius: 6px;
    cursor: pointer;
  }
  
  strong {
    color: #059669;
  }
  
  span {
    font-weight: bold;
    color: #059669;
  }
  
  code {
    background: #f0fdf4;
    padding: 0.2rem 0.4rem;
    border-radius: 4px;
    color: #059669;
  }
`;
      document.head.appendChild(s);
    }
  }

  return __LUMIX__.h(__LUMIX__.Fragment, null, __LUMIX__.h('div', {
    'class': 'page'
  }, [
    `
  `,
    __LUMIX__.h('h1', null, [
      `About (Server-Side)`
    ]),
    `
  `,
    __LUMIX__.h('p', null, [
      `This page uses `,
      __LUMIX__.h('code', null, [
        `"use server"`
      ]),
      ` directive for SSR.`
    ]),
    `
  `,
    __LUMIX__.h('p', null, [
      `Server timestamp: `,
      __LUMIX__.h('strong', null, [
        () => (serverTime)
      ])
    ]),
    `
  `,
    __LUMIX__.h('p', null, [
      `User agent: `,
      __LUMIX__.h('strong', null, [
        () => (userAgent)
      ])
    ]),
    `
  `,
    __LUMIX__.h('p', null, [
      `Interactive counter: `,
      __LUMIX__.h('span', null, [
        () => (count())
      ])
    ]),
    `
  `,
    __LUMIX__.h('button', {
      'onclick': ()=>count(count() + 1)
    }, [
      `Increment`
    ]),
    `
  
  `,
    __LUMIX__.h('nav', {
      'class': 'nav'
    }, [
      `
    `,
      __LUMIX__.h('a', {
        'href': '/'
      }, [
        `← Back to Home`
      ]),
      `
  `
    ]),
    `
`
  ]), `

`);
}
export default about;
export { about };
const __LUMIX_ROOT__ = about;

export function hydrate(root, props) {
  __LUMIX__.hydrate(root, about, props);
}
