// Generated by LumixJS
import * as __LUMIX__ from 'lumix-js';
import { signal } from "lumix-js";

function Counter(props = {}) {
  let { initialCount = 0, label = "Count" } = props;

  const count = signal(initialCount);
  function increment() {
      count(count() + 1);
  }
  function decrement() {
      count(count() - 1);
  }
  function reset() {
      count(initialCount);
  }

  // Styles
  if (typeof document !== 'undefined') {
    const styleId = 'lumix-style-counter';
    if (!document.getElementById(styleId)) {
      const s = document.createElement('style');
      s.id = styleId;
      s.textContent = `
  .counter {
    background: rgba(24, 24, 27, 0.6);
    border: 1px solid rgba(139, 92, 246, 0.2);
    border-radius: 16px;
    padding: 2.5rem;
    text-align: center;
    backdrop-filter: blur(12px);
  }
  
  .counter h3 {
    margin: 0 0 1.5rem 0;
    color: #e4e4e7;
    font-size: 1.125rem;
    font-weight: 600;
    letter-spacing: 0.025em;
  }
  
  .display {
    font-size: 4rem;
    font-weight: 700;
    background: linear-gradient(135deg, #8b5cf6 0%, #ec4899 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
    margin: 1.5rem 0;
    font-variant-numeric: tabular-nums;
  }
  
  .buttons {
    display: flex;
    gap: 0.75rem;
    justify-content: center;
    margin-top: 2rem;
  }
  
  .btn {
    padding: 0.75rem 1.5rem;
    border: none;
    border-radius: 10px;
    font-size: 0.9375rem;
    font-weight: 600;
    cursor: pointer;
    transition: all 0.2s;
    font-family: inherit;
  }
  
  .btn-primary {
    background: linear-gradient(135deg, #8b5cf6 0%, #7c3aed 100%);
    color: white;
    box-shadow: 0 4px 12px rgba(139, 92, 246, 0.3);
  }
  
  .btn-primary:hover {
    transform: translateY(-2px);
    box-shadow: 0 6px 16px rgba(139, 92, 246, 0.4);
  }
  
  .btn-secondary {
    background: rgba(63, 63, 70, 0.6);
    color: #e4e4e7;
    border: 1px solid rgba(255, 255, 255, 0.1);
  }
  
  .btn-secondary:hover {
    background: rgba(82, 82, 91, 0.6);
  }
  
  .btn:active {
    transform: translateY(0);
  }
`;
      document.head.appendChild(s);
    }
  }

  return __LUMIX__.h(__LUMIX__.Fragment, null, __LUMIX__.h('div', {
    'class': 'counter'
  }, [
    `
  `,
    __LUMIX__.h('h3', null, [
      () => (label)
    ]),
    `
  `,
    __LUMIX__.h('div', {
      'class': 'display'
    }, [
      () => (count())
    ]),
    `
  `,
    __LUMIX__.h('div', {
      'class': 'buttons'
    }, [
      `
    `,
      __LUMIX__.h('button', {
        'onclick': decrement,
        'class': 'btn btn-secondary'
      }, [
        `-`
      ]),
      `
    `,
      __LUMIX__.h('button', {
        'onclick': reset,
        'class': 'btn btn-secondary'
      }, [
        `Reset`
      ]),
      `
    `,
      __LUMIX__.h('button', {
        'onclick': increment,
        'class': 'btn btn-primary'
      }, [
        `+`
      ]),
      `
  `
    ]),
    `
`
  ]), `

`);
}
export default Counter;
export { Counter };
const __LUMIX_ROOT__ = Counter;

export function hydrate(root, props) {
  __LUMIX__.hydrate(root, Counter, props);
}
