// Generated by LumixJS
import * as __LUMIX__ from 'lumix-js';
import { signal } from "lumix-js";

function index(props = {}) {
  "use static";
  const buildTime = new Date().toISOString();
  const count = signal(0);

  // Styles
  if (typeof document !== 'undefined') {
    const styleId = 'lumix-style-index';
    if (!document.getElementById(styleId)) {
      const s = document.createElement('style');
      s.id = styleId;
      s.textContent = `
  .page {
    max-width: 640px;
    margin: 0 auto;
    padding: 2rem;
    font-family: system-ui, sans-serif;
  }
  
  h1 { color: #4f46e5; }
  
  .info {
    margin: 2rem 0;
    padding: 1rem;
    background: #fef3c7;
    border-left: 4px solid #f59e0b;
    border-radius: 4px;
  }
  
  .info h3 {
    margin-top: 0;
    color: #92400e;
  }
  
  .info strong {
    color: #92400e;
  }
  
  .nav {
    margin: 2rem 0;
    padding: 1rem;
    background: #f8fafc;
    border-radius: 8px;
  }
  
  .nav h3 {
    margin-top: 0;
    color: #374151;
  }
  
  .nav a {
    display: block;
    margin: 0.5rem 0;
    padding: 0.5rem;
    color: #4f46e5;
    text-decoration: none;
    border-radius: 4px;
    transition: background-color 0.2s;
  }
  
  .nav a:hover {
    background: #e0e7ff;
  }
  
  .demo {
    margin: 2rem 0;
    padding: 1rem;
    border: 2px dashed #4f46e5;
    border-radius: 8px;
  }
  
  code { 
    background: #f3f4f6; 
    padding: 0.2rem 0.4rem; 
    border-radius: 4px; 
  }
  
  button {
    margin-top: 1rem;
    padding: 0.5rem 1rem;
    background: #4f46e5;
    color: white;
    border: none;
    border-radius: 6px;
    cursor: pointer;
  }
`;
      document.head.appendChild(s);
    }
  }

  return __LUMIX__.h(__LUMIX__.Fragment, null, __LUMIX__.h('div', {
    'class': 'page'
  }, [
    `
  `,
    __LUMIX__.h('h1', null, [
      `Lumix (Static Site Generation)`
    ]),
    `
  `,
    __LUMIX__.h('p', null, [
      `Meta-framework template. Edit `,
      __LUMIX__.h('code', null, [
        `src/routes/index.lumix`
      ]),
      `.`
    ]),
    `
  
  `,
    __LUMIX__.h('div', {
      'class': 'info'
    }, [
      `
    `,
      __LUMIX__.h('h3', null, [
        `SSG vs SSR:`
      ]),
      `
    `,
      __LUMIX__.h('p', null, [
        __LUMIX__.h('strong', null, [
          `Esta página (SSG):`
        ]),
        ` Generada una vez en build time. El timestamp NO cambia al recargar.`
      ]),
      `
    `,
      __LUMIX__.h('p', null, [
        `Build timestamp: `,
        __LUMIX__.h('strong', null, [
          () => (buildTime)
        ])
      ]),
      `
    `,
      __LUMIX__.h('p', null, [
        __LUMIX__.h('em', null, [
          `Recarga la página varias veces - el timestamp permanece igual porque es estático.`
        ])
      ]),
      `
  `
    ]),
    `
  
  `,
    __LUMIX__.h('nav', {
      'class': 'nav'
    }, [
      `
    `,
      __LUMIX__.h('h3', null, [
        `Navigation:`
      ]),
      `
    `,
      __LUMIX__.h('a', {
        'href': '/'
      }, [
        `Home (Static - "use static")`
      ]),
      `
    `,
      __LUMIX__.h('a', {
        'href': '/about'
      }, [
        `About (Server - "use server")`
      ]),
      `
  `
    ]),
    `
  
  `,
    __LUMIX__.h('div', {
      'class': 'demo'
    }, [
      `
    `,
      __LUMIX__.h('p', null, [
        `Interactive counter (island hidratada en cliente):`
      ]),
      `
    `,
      __LUMIX__.h('button', {
        'onclick': ()=>count(count() + 1)
      }, [
        `Count: `,
        () => (count())
      ]),
      `
    `,
      __LUMIX__.h('p', null, [
        __LUMIX__.h('em', null, [
          `Este contador funciona porque se hidrata en el cliente, pero el HTML inicial es estático.`
        ])
      ]),
      `
  `
    ]),
    `
`
  ]), `

`);
}
export default index;
export { index };
const __LUMIX_ROOT__ = index;

export function hydrate(root, props) {
  __LUMIX__.hydrate(root, index, props);
}
