// Generated by LumixJS
import * as __LUMIX__ from 'lumix-js';
import MainLayout from 'file:///F:/LuminJS/tests/full-stack-test/.lumix/compiled/layouts-MainLayout.mjs';
import Counter from 'file:///F:/LuminJS/tests/full-stack-test/.lumix/compiled/components-Counter.mjs';

function index(props = {}) {
  "use prerender";

  // Styles
  if (typeof document !== 'undefined') {
    const styleId = 'lumix-style-index';
    if (!document.getElementById(styleId)) {
      const s = document.createElement('style');
      s.id = styleId;
      s.textContent = `
  .page {
    font-family: system-ui, -apple-system, sans-serif;
  }
  
  .hero {
    text-align: center;
    margin-bottom: 4rem;
  }
  
  .hero-logo {
    display: block;
    margin: 0 auto 2rem;
    opacity: 0.9;
  }
  
  h1 {
    font-size: 3.5rem;
    margin: 0 0 1rem 0;
    background: linear-gradient(135deg, #8b5cf6 0%, #ec4899 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
    font-weight: 800;
    letter-spacing: -0.02em;
  }
  
  .subtitle {
    font-size: 1.25rem;
    color: #a1a1aa;
    margin: 0;
    font-weight: 400;
  }
  
  .info-card {
    background: rgba(24, 24, 27, 0.6);
    border: 1px solid rgba(139, 92, 246, 0.2);
    border-radius: 16px;
    padding: 2rem;
    margin: 3rem 0;
    backdrop-filter: blur(12px);
  }
  
  .card-icon {
    width: 48px;
    height: 48px;
    background: linear-gradient(135deg, #8b5cf6 0%, #7c3aed 100%);
    border-radius: 12px;
    display: flex;
    align-items: center;
    justify-content: center;
    margin-bottom: 1.5rem;
  }
  
  .card-icon svg {
    color: white;
  }
  
  .card-icon img {
    display: block;
    filter: brightness(0) saturate(100%) invert(100%);
  }
  
  .info-card h2 {
    margin: 0 0 1rem 0;
    color: #e4e4e7;
    font-size: 1.5rem;
    font-weight: 700;
  }
  
  .info-card p {
    color: #a1a1aa;
    line-height: 1.6;
    margin: 0 0 1.5rem 0;
  }
  
  .info-card ul {
    list-style: none;
    margin: 0;
    padding: 0;
    display: flex;
    flex-direction: column;
    gap: 0.75rem;
  }
  
  .info-card li {
    display: flex;
    align-items: center;
    gap: 0.75rem;
    color: #d4d4d8;
  }
  
  .info-card li svg {
    color: #8b5cf6;
    flex-shrink: 0;
  }
  
  .info-card li img {
    flex-shrink: 0;
    filter: brightness(0) saturate(100%) invert(52%) sepia(98%) saturate(3283%) hue-rotate(242deg) brightness(96%) contrast(91%);
  }
  
  .demo-section {
    margin: 4rem 0;
  }
  
  .demo-section h2 {
    text-align: center;
    margin-bottom: 2rem;
    color: #e4e4e7;
    font-size: 2rem;
    font-weight: 700;
  }
  
  .features {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
    gap: 1.5rem;
    margin: 4rem 0;
  }
  
  .feature {
    background: rgba(24, 24, 27, 0.4);
    border: 1px solid rgba(255, 255, 255, 0.1);
    border-radius: 16px;
    padding: 2rem;
    transition: all 0.3s;
  }
  
  .feature:hover {
    transform: translateY(-4px);
    border-color: rgba(139, 92, 246, 0.3);
    box-shadow: 0 12px 24px rgba(139, 92, 246, 0.1);
  }
  
  .feature-icon {
    width: 48px;
    height: 48px;
    background: rgba(139, 92, 246, 0.1);
    border-radius: 12px;
    display: flex;
    align-items: center;
    justify-content: center;
    margin-bottom: 1.5rem;
  }
  
  .feature-icon svg {
    color: #8b5cf6;
  }
  
  .feature-icon img {
    display: block;
    filter: brightness(0) saturate(100%) invert(52%) sepia(98%) saturate(3283%) hue-rotate(242deg) brightness(96%) contrast(91%);
  }
  
  .feature h3 {
    margin: 0 0 0.75rem 0;
    color: #e4e4e7;
    font-size: 1.25rem;
    font-weight: 600;
  }
  
  .feature p {
    margin: 0;
    color: #a1a1aa;
    line-height: 1.6;
  }
  
  [slot="footer"] a {
    color: #8b5cf6;
    text-decoration: none;
    font-weight: 500;
  }
  
  [slot="footer"] a:hover {
    text-decoration: underline;
  }
`;
      document.head.appendChild(s);
    }
  }

  return __LUMIX__.h(__LUMIX__.Fragment, null, __LUMIX__.h(MainLayout, {
    'children': () => [
      `
  `,
      __LUMIX__.h('div', {
        'class': 'page'
      }, [
        `
    `,
        __LUMIX__.h('div', {
          'class': 'hero'
        }, [
          `
      `,
          __LUMIX__.h('img', {
            'src': '/icons/logo.svg',
            'alt': 'Lumix',
            'class': 'hero-logo',
            'width': '80',
            'height': '80'
          }),
          `
      `,
          __LUMIX__.h('h1', null, [
            `Welcome to Lumix`
          ]),
          `
      `,
          __LUMIX__.h('p', {
            'class': 'subtitle'
          }, [
            `A high-performance web framework with Progressive Instant Rendering`
          ]),
          `
    `
        ]),
        `
    
    `,
        __LUMIX__.h('div', {
          'class': 'info-card'
        }, [
          `
      `,
          __LUMIX__.h('div', {
            'class': 'card-icon'
          }, [
            `
        `,
            __LUMIX__.h('img', {
              'src': '/icons/activity.svg',
              'alt': '',
              'width': '24',
              'height': '24'
            }),
            `
      `
          ]),
          `
      `,
          __LUMIX__.h('h2', null, [
            `Progressive Instant Rendering (PIR)`
          ]),
          `
      `,
          __LUMIX__.h('p', null, [
            `This page is prerendered at build time for instant loads and perfect SEO, then fully hydrated on the client for complete interactivity.`
          ]),
          `
      `,
          __LUMIX__.h('ul', null, [
            `
        `,
            __LUMIX__.h('li', null, [
              `
          `,
              __LUMIX__.h('img', {
                'src': '/icons/check.svg',
                'alt': '',
                'width': '16',
                'height': '16'
              }),
              `
          Instant page loads
        `
            ]),
            `
        `,
            __LUMIX__.h('li', null, [
              `
          `,
              __LUMIX__.h('img', {
                'src': '/icons/check.svg',
                'alt': '',
                'width': '16',
                'height': '16'
              }),
              `
          Perfect SEO
        `
            ]),
            `
        `,
            __LUMIX__.h('li', null, [
              `
          `,
              __LUMIX__.h('img', {
                'src': '/icons/check.svg',
                'alt': '',
                'width': '16',
                'height': '16'
              }),
              `
          Full client-side interactivity
        `
            ]),
            `
      `
          ]),
          `
    `
        ]),
        `
    
    `,
        __LUMIX__.h('div', {
          'class': 'demo-section'
        }, [
          `
      `,
          __LUMIX__.h('h2', null, [
            `Interactive Component Demo`
          ]),
          `
      `,
          __LUMIX__.h(Counter, {
            'initialCount': 0,
            'label': 'Click Counter'
          }),
          `
    `
        ]),
        `
    
    `,
        __LUMIX__.h('div', {
          'class': 'features'
        }, [
          `
      `,
          __LUMIX__.h('div', {
            'class': 'feature'
          }, [
            `
        `,
            __LUMIX__.h('div', {
              'class': 'feature-icon'
            }, [
              `
          `,
              __LUMIX__.h('img', {
                'src': '/icons/zap.svg',
                'alt': '',
                'width': '24',
                'height': '24'
              }),
              `
        `
            ]),
            `
        `,
            __LUMIX__.h('h3', null, [
              `Fast`
            ]),
            `
        `,
            __LUMIX__.h('p', null, [
              `Native Rust compiler for near-instant builds`
            ]),
            `
      `
          ]),
          `
      `,
          __LUMIX__.h('div', {
            'class': 'feature'
          }, [
            `
        `,
            __LUMIX__.h('div', {
              'class': 'feature-icon'
            }, [
              `
          `,
              __LUMIX__.h('img', {
                'src': '/icons/smile.svg',
                'alt': '',
                'width': '24',
                'height': '24'
              }),
              `
        `
            ]),
            `
        `,
            __LUMIX__.h('h3', null, [
              `Reactive`
            ]),
            `
        `,
            __LUMIX__.h('p', null, [
              `Fine-grained reactivity with signals`
            ]),
            `
      `
          ]),
          `
      `,
          __LUMIX__.h('div', {
            'class': 'feature'
          }, [
            `
        `,
            __LUMIX__.h('div', {
              'class': 'feature-icon'
            }, [
              `
          `,
              __LUMIX__.h('img', {
                'src': '/icons/settings.svg',
                'alt': '',
                'width': '24',
                'height': '24'
              }),
              `
        `
            ]),
            `
        `,
            __LUMIX__.h('h3', null, [
              `Flexible`
            ]),
            `
        `,
            __LUMIX__.h('p', null, [
              `PIR, SSR, and SSG rendering modes`
            ]),
            `
      `
          ]),
          `
    `
        ]),
        `
  `
      ]),
      `
  
  `,
      `
`
    ],
    'slots': {
      'footer': () => [
        __LUMIX__.h('div', {
                  }, [
          `
    `,
          __LUMIX__.h('p', null, [
            `Built with Lumix • `,
            __LUMIX__.h('a', {
              'href': 'https://github.com/ZtaMDev/Lumix',
              'target': '_blank'
            }, [
              `GitHub`
            ])
          ]),
          `
  `
        ])
      ]
    }
  }), `

`);
}
export default index;
export { index };
const __LUMIX_ROOT__ = index;

// Head metadata
export const head = {title: "Home - Lumix Framework", meta: [{"content":"Welcome to Lumix - A high-performance web framework with Progressive Instant Rendering","name":"description"},{"content":"Lumix Framework","property":"og:title"},{"content":"High-performance web framework with PIR","property":"og:description"},{"name":"keywords","content":"lumix, web framework, PIR, progressive rendering"}]};

export function hydrate(root, props) {
  __LUMIX__.hydrate(root, index, props);
}
